### ISSUE TITLE
Описание предметной области 

### ISSUE THREAD

**Issue by RomanovskiyIlya** [RomanovskiyIlya/kursovaya#4]

**Comment by RomanovskiyIlya** [comment]
Описание предметной области.

Люди покупают автомобили по множеству различных причин, которые могут варьироваться в зависимости от индивидуальных потребностей, обстоятельств и жизненных стилей. 

На рынке существует множество различных **марок** автомобилей, каждая из которых имеет свои характерные особенности, историю и репутацию. Марки автомобилей разделяются по странам происхождения, классам и типам автомобилей. У каждой марки есть **модели,** а у каждой модели по несколько **комплектаций**. Комплектация автомобиля - это набор опций, оснащения, функций и **характеристик**, которые поставляются с автомобилем при его производстве или продаже. Комплектация определяет, какие особенности и уровень комфорта будет иметь конкретный автомобиль, а также его цену.
Обычно производители предлагают несколько различных комплектаций для каждой модели, начиная с базовой и заканчивая более роскошными или высокотехнологичными вариантами.
Характеристики автомобиля - это технические данные и параметры, которые определяют его производительность, способность и функциональные возможности. Они являются важными при выборе автомобиля, так как помогают определить, насколько он подходит для конкретных потребностей и предпочтений владельца. 

Вот основные характеристики автомобилей:
Мощность двигателя (л.с. или кВт): Это параметр, определяющий мощность двигателя и его способность развивать скорость. Чем выше мощность, тем быстрее и мощнее автомобиль.
Объем двигателя (кубические сантиметры или литры): Объем двигателя указывает на его размер и вместимость для воздушно-топливной смеси. Он может влиять на расход топлива и момент.
Тип двигателя: Это может быть бензиновый, дизельный, гибридный или электрический двигатель. Тип двигателя влияет на эффективность и экологичность автомобиля.
Расход топлива (город/трасса/смешанный): Эта характеристика показывает, сколько топлива автомобиль потребляет на определенное расстояние при движении в городе, на трассе и в смешанных условиях.
Тип трансмиссии: Это указывает на то, какая коробка передач установлена в автомобиле, например, механическая, автоматическая, роботизированная или вариатор.
Система привода: Это определяет, какие колеса приводят автомобиль: передние, задние или полный привод.
Скорость разгона (0-100 км/ч): Этот параметр показывает, сколько времени автомобилю требуется для разгона с нуля до 100 км/ч.
Габариты и вес: Габариты автомобиля, такие как длина, ширина и высота, могут влиять на его маневренность и вместимость. Вес также может влиять на производительность и расход топлива.
Выбор конкретных характеристик завит от потребностей, бюджета и предпочтений покупателя.


С уходом из России почти всех автомобильных брендов, их представительств и официальных дилеров у людей появился вопрос, какую машину купить. Есть 3 варианта.
Либо идти и купить авто Российского или китайского бренда, либо пойти на доски объявлений и купить авто с рук, где никаких гарантий и уверенности в прошлом автомобиля нет, либо воспользоваться услугами компаний, которые занимаются импортом авто из других стран. Самые популярные направления это: 

1)Япония
2)Южная Корея
3)Китай

Из Японии привозят авто с правым рулем, при этом не обязательно это авто японских брендов. Преимущества импорта авто из Японии в том, что цены там сильно ниже, все продажи идут с аукционов, что гарантирует честность информации о машине, и автомобили японской сборки славятся своим качеством и своей надежностью. Есть и минусы. Во первых из Японии привозят только праворульные авто. Во вторых Япония ввела санкции против России и теперь нельзя вывозить в Россию гибридные авто, электрические авто и автомобили с двигателем внутреннего сгорания объемом больше 2 литров.
	Из Кореи привозят автомобили с более привычным левым рулем, и не только корейских брендов. Преимущества в том, что цены все еще ниже, чем в России, сборка и комплектации лучше, и состояние автомобилей тоже лучше, что связанно по большей степени с качеством дорожного покрытия. Минусы также есть. Они заключаются в меньшей надежности информации об покупаемом авто. Это связанно с тем, что продажа авто там происходит не с аукционов как в Японии, а с досок объявлений как у нас в России.
	Из Китая в основном привозят авто китайских брендов, и в основном в состоянии новых или прямо из салона. Это выходит дешевле, чем купить такую же машину в России у официального дилера. И выбор там, конечно, больше.

	


Как происходит процесс заказа покупки авто?

Сначала человек выбирает компанию, которая будет заниматься покупкой, оформлением и транспортировкой. После выбора компании обычно сразу с сайта человек берет контакты менеджера или оставляет **заявку** на консультацию. Связавшись с менеджером,  человек начинает выбирать автомобиль, спрашивает у менеджера какие машины можно привести в Россию, какие у них комплектации и так далее. У человека, который не знает, какой автомобиль ему нужен это займет некоторое время. Далее подписывается договор и вносится предоплата (у разных компаний по разному). После начинается процесс подбора авто. Менеджер присылает варианты автомобилей, называет их цену, комплектацию. Когда найден автомобиль, устраивающий клиента, он бронируется и клиенту высылается Invois(инвойс). На его оплату дается 3-5 дней . Инвойс – это документ, объединяющий функции товарной накладной, акта выполненных работ и счета на оплату; он подтверждает цену и государство, где был произведен продукт. С английского invoice так и переводится – счет. После покупки автомобиля начинается процесс его оформление. **Клиент** присылает все необходимые документы и автомобиль оформляют на него. Автомобиль перевозят в Россию. На этапе Российской таможни вносится последняя часть оплаты – расходы за таможенное оформление. 
После всех этих действий автомобиль клиента оказывается на стоянке компании. По желанию клиента его ставят на учет. Клиент может приехать за своим авто сам, или, если он живет в другом конце страны, заказать его доставку до своего города.

**Comment by wldmr-key** [comment]
попробуй сформатировать текст, чтобы при чтении не шла кровь из глаз

**Comment by wldmr-key** [comment]
Ты правильно сделал, что попытался сформулировать описание предметной области. Это, надеюсь, позволит довести до конца многострадальное ТЗ

Воду в начале убирай безусловно

Теперь попробуем добраться до процесса, который ты собираешься автоматизировать

> Связавшись с менеджером, человек начинает выбирать автомобиль, спрашивает у менеджера какие машины можно, какие нельзя, какие у них комплектации и так далее

вряд ли человек начинает выбирать автомобиль только связавшись с менеджером. Вряд ли его сильно интересует вопрос, какие машины купить нельзя

> У человека, который не знает, какой автомобиль ему нужен это займет некоторое время.

вот этот процесс ты автоматизируешь

> Далее подписывается договор и вносится предоплата (у разных компаний по разному). После начинается процесс подбора авто. 

а, вот отсюда уже без тебя. 

Я правильно понял?

**Comment by RomanovskiyIlya** [comment]
Да, вы правильно поняли, что автоматизировать я хочу процесс выбора авто и консультаций по поводу его характеристик. Подписание договоров мои планы пока не входит.

Я отформатировал текст, и убрал воды, и чтобы не пересылать еще раз огромное сообщение изменил первое.


Еще дополнение к предметной области.

Стоит учесть, что у процесса заказа авто есть некоторые трудности. Первый нюанс в различии авторынков России и азиатских стран. Многие машины, которые продаются у там, не представлены в России. Соответственно человек, который захочет заказать авто из Японии, Кореи или Китая не знает про ассортимент автомобилей там. Второй нюанс это различие характеристик авто, которые шли на наш рынок и тех, которые шли на внутренний рынок этих стран. У них может отличаться мощность мотора, привод (полный, передний), клиренс и комплектации. Это тоже играет важную роль при выборе авто. Не каждый захочет купить автомобиль и узнать, что в нем стоит двигатель, например, на 252 лошадиные силы вместо 250 как этот же автомобиль продается в России.(Суть в том, что налог на мощность 250 л.с. составляет около 18000 рублей, а от 251 л.с налог будет уже 36000 рублей, что в 2 раза больше)
Третий нюанс заключается в общении с менеджерами компании, которые будут помогать вам с выбором и покупкой. Проблема в том, что большинство подобных компаний находятся во Владивостоке. Розница в часовых поясах с европейской частью России у которого составляет 7 часов. Из за этого, когда клиент пишет своему менеджеру в удобное для себя время, у менеджера рабочий день уже закончился, и наоборот, когда менеджер отвечает клиенту, он скорее всего еще спит. Также не стоит забывать про огромную загруженность менеджеров.
По итогу трех проблем общение с менеджером по поводу выбора автомобиля и уточнения его характеристик может затянуться на недели.

**Comment by wldmr-key** [comment]
ок, описание можно считать превосходным. Пора формулировать требования к системе ))

**Comment by RomanovskiyIlya** [comment]
Требования к системе:
1. Реализовать актуальный каталог автомобилей, доступных для заказа.
2. Реализовать способ добавления новых автомобилей в каталог.
3. Функция аутентификации и регистрации.
4. Функция поиска модели автомобиля по названию.
5. Функция поиска моделей автомобилей по фильтру характерискик.

На самом деле пока что слабо понимаю различие между тем, какие требования должны быть тут и теми, которые в ТЗ.

И еще вопрос. Вы мне на консультации сказали подробнее описать принципы ценообразования. Это нужно дописывать в предметную область?

**Comment by wldmr-key** [comment]
Требования к системе должны вытекать из ТЗ и описания предметной области и так формулироваться, чтобы включить в себя все сущности, атрибуты и связи, которые будут фигурировать в БД. Поэтому дублировать ТЗ совершенно не следует.

Начну за тебя: разрабатывемая система автоматизирует процес ...

Клиент для использоавния системы должен зарегистрироваться, введя ...

Для подбора автомобиля он вводит... выбирает... пишет ... рисует...видит...

После выбора модели он ....

Со стороны сервиса персонал должен ввести..., вывести... увести..

и так далее...

> И еще вопрос. Вы мне на консультации сказали подробнее описать принципы ценообразования. Это нужно дописывать в предметную область?

я не помню. Скорее всего клиент должен в твоей системе увидеть все деньги, которые он должен заплатить и понять, за что он платит. А также понять гарантии того, что он их платит не зря

**Comment by RomanovskiyIlya** [comment]
Требования к системе:
1. Разрабатываемая система автоматизирует процесс выбора модели автомобиля клиентом.
2. Клиент для использования системы должен зарегистрироваться, введя Логин (номер телефона), Имя и пароль.
3. Для выбора автомобиля клиент может воспользоваться окном поиска моделей по названию, фильтром характерискик  или перейти к списку брендов, после ного к списку моделей и, в конечном итоге, увидит список комплектаций выбранной модели.
4. После выбора комплектации, клиент видит ориентировочную стоимость автомобиля. 
5. После выбора модели, клиент нажимает на кнопку "оставить заявку" , которая будет находиться на одной странице с выбранной моделью или ее комплектацией.
6. Со стороны сервиса персонал входит в систему вводя свой логин и пароль.
7. После входа в систему персонал может управлять каталогом, а именно: добавлять в систему новые бренды, модели, комплектации и редактировать их характеристики, скрывать конкретные модели и их комплектации.

**Comment by wldmr-key** [comment]
Желательно требования к систем оформить таким же связным рассказом, как и описание предметной области.

Что кроме стоимости и характеристик модели влияет на решение о покупке?

**Comment by RomanovskiyIlya** [comment]
> Что кроме стоимости и характеристик модели влияет на решение о покупке?

Возможно для кого-то будут играть роль сроки доставки.

**Comment by wldmr-key** [comment]
а что? Бывают такие, которым эти сроки по барабану?

**Comment by RomanovskiyIlya** [comment]
Разрабатываемая система автоматизирует процесс выбора модели автомобиля клиентом.
Чтобы воспользоваться системой клиент должен авторизоваться или зарегистрироваться, введя логин, пароль и имя.
После входа в систему клиент может приступить к выбору автомобиля. Для этого он может воспользоваться окном поиска моделей по названию, фильтром характерискик или перейти к списку производителей, после ного к списку моделей и, в конечном итоге, увидит список комплектаций выбранной модели. После того, как клиент выбрал автомобиль, он может узнать его ориентировочную стоимость и сроки доставки. Так же клиент может оставить заявку и подождать, когда с ним свяжется менеджер компании для подписания договора.
У системы должны быть администраторы. Они входят в систему под своими логинами и паролями. Зарегистрировать нового администратора может только администратор. Администраторы могут управлять каталогом, а именно: добавлять в систему новых производителей, модели, комплектации и редактировать их характеристики, скрывать конкретные модели и их комплектации.

>а что? Бывают такие, которым эти сроки по барабану?

лично мне не принципиально приедет машина через 1 неделю или через 5. В среднем на сегодняшний день срок доставки составляет 45 дней. Но, соглашусь, что знать сроки доставки клиентам нужно. Я добавил это в требования.

**Comment by wldmr-key** [comment]
все неплохо, но из твоего описания совершенно неочевидны связи администраторов, которые появятся в концептуальной схеме

Не уверен в полноте атрибутов комплектации

я правильно понимаю, что выбор клиента имеет предварительный характер и может быть радикально изменен после разговоров с менеджером (и это в твоей системе никак не обнаружится)

**Comment by RomanovskiyIlya** [comment]
>из твоего описания совершенно неочевидны связи администраторов, которые появятся в концептуальной схеме

не совсем понял.

>я правильно понимаю, что выбор клиента имеет предварительный характер и может быть радикально изменен после разговоров с менеджером (и это в твоей системе никак не обнаружится)

Да, выбор автомобиля в системе не к чему не обязывает. Только после подписания договора клиент не может радикально поменять свой выбор.

**Comment by wldmr-key** [comment]
> не совсем понял.

а че ж на консультации не спросил? ))
