### ISSUE TITLE
Логическая схема

### ISSUE THREAD

**Issue by RomanovskiyIlya** [RomanovskiyIlya/kursovaya#7]
![image](https://github.com/RomanovskiyIlya/kursovaya/assets/121176869/7507354f-1eb9-49b1-bd36-b3eeab3613b5)

**Comment by wldmr-key** [comment]
внимательно проверь таблицу "Заявки" ты там накосил с атрибутами и внешними ключами

**Comment by RomanovskiyIlya** [comment]
![image](https://github.com/RomanovskiyIlya/kursovaya/assets/121176869/048c92d0-3ced-48e9-8b5a-6f153082ee0d)

внешние ключи лишние
